<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-TU5HT4T" failures="1" tests="1" name="Test(failed)" time="0.038" errors="0" timestamp="05 Aug 2023 12:35:58 GMT">
  <testcase classname="org.Example.A" name="Tc01" time="0.015">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Enter Correct name expected [Kayal] but found [Logesh]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Enter Correct name expected [Kayal] but found [Logesh]
at org.Example.A.Tc01(A.java:19)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- Tc01 -->
  <testcase classname="org.Example.A" name="Tc02" time="0.0">
    <ignored/>
  </testcase> <!-- Tc02 -->
  <testcase classname="org.Example.A" name="Tc03" time="0.0">
    <ignored/>
  </testcase> <!-- Tc03 -->
</testsuite> <!-- Test(failed) -->
